FROM ubuntu:12.04

COPY sources.list /etc/apt/

RUN apt-get update && \
    apt-get -y install llvm-2.8-dev llvm-gcc-4.6 zip unzip git g++ libgc-dev libfcgi-dev gdb make libc6-dev

COPY fixuid /usr/local/bin

RUN USER=dev && \
    GROUP=dev && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

RUN addgroup --gid 1000 dev && \
    adduser --uid 1000 --ingroup dev --home /home/dev --shell /bin/sh --disabled-password --gecos "" dev && \
    mkdir /home/dev/source && \
    chown dev:dev /home/dev/source

VOLUME /home/dev/source/