version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull
          command: git pull --ff-only origin master
      - run:
          name: DockerLogin
          command: ./docker-login.sh
      - run:
          name: Bootstrap
          command: WORKSPACE=`pwd` BUILD_NUMBER=$((400+CIRCLE_BUILD_NUM)) ./ci-bootstrap.sh

  push:
    machine: true  
    steps:
      - checkout
      - run:
          name: Push
          command: git push origin master

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: WORKSPACE=`pwd` BUILD_NUMBER=$((400+CIRCLE_BUILD_NUM)) ./ci-build.sh
      - run:
          name: DockerLogin
          command: ./docker-login.sh
      - run:
          name: BuildAndPushImage
          command: ./ci-deploy.sh

workflows:
  version: 2
  build_push_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

      - push:
          requires:
            - build
          filters:
            branches:
              ignore: master

      - deploy:
          filters:
            branches:
              only: master

