#K
namespace System is
    /// Constants describing machine name and sizes of primitive integer types
    class Environment is
        const int WORD_BITS = 64;
	const int WORD_MASK = 63;
	const int WORD_SHIFT = 6;
	const int WORD_BYTES = 8;

	const int LONG_BITS = 64;
	const int LONG_SHIFT = 6;
	const int LONG_BYTES = 8;

	const int INT_BITS = 32;
	const int INT_SHIFT = 5;
	const int INT_BYTES = 4;
    si
si
